apiVersion: v1
kind: Secret
metadata:
  name: autoservice-app-secret
  namespace: autoservice
type: Opaque
stringData:
  AUTOSERVICE_JWT_SECRET: change-me-same-secret-as-auth-worker
  SPRING_DATASOURCE_PASSWORD: change-me-from-infra-db-output
  MAIL_USERNAME: your-smtp-user
  MAIL_PASSWORD: your-smtp-password
