apiVersion: v1
kind: Secret
metadata:
  name: autoservice-app-secret
  namespace: autoservice
type: Opaque
stringData:
  AUTOSERVICE_JWT_SECRET: change-me-before-deploy
  MAIL_USERNAME: your-smtp-user
  MAIL_PASSWORD: your-smtp-password
