apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: autoservice-postgres-pvc
  namespace: autoservice
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi

