apiVersion: v1
kind: ConfigMap
metadata:
  name: autoservice-config
  namespace: autoservice
  labels:
    app.kubernetes.io/name: autoservice
    app.kubernetes.io/part-of: autoservice
data:
  SPRING_DATASOURCE_URL: "jdbc:postgresql://autoservice-postgres:5432/autoservice"
  APP_BASE_URL: "http://autoservice.local"
  MAIL_HOST: "mailhog"
  MAIL_PORT: "1025"
  MAIL_SMTP_AUTH: "false"
  MAIL_SMTP_STARTTLS: "false"
  MAIL_FROM: "orcamentos@autoservice.local"
  AUTOSERVICE_NOTIFICACAO_SIMULADA_HABILITADA: "true"
  JAVA_OPTS: "-XX:MaxRAMPercentage=75.0"
