apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: autoservice
resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - postgres.yaml
  - deployment.yaml
  - service.yaml
  - hpa.yaml
  - ingress.yaml

images:
  - name: autoservice
    newName: ghcr.io/owner/autoservice
    newTag: latest
