apiVersion: v1
kind: Secret
metadata:
  name: autoservice-secret
  namespace: autoservice
  labels:
    app.kubernetes.io/name: autoservice
    app.kubernetes.io/part-of: autoservice
type: Opaque
stringData:
  SPRING_DATASOURCE_USERNAME: "postgres"
  SPRING_DATASOURCE_PASSWORD: "postgres"
  AUTOSERVICE_JWT_SECRET: "troque-por-um-segredo-forte-e-aleatorio-em-producao"
  MAIL_USERNAME: ""
  MAIL_PASSWORD: ""
  AUTOSERVICE_NOTIFICACAO_WEBHOOK_URL: ""
---
apiVersion: v1
kind: Secret
metadata:
  name: autoservice-postgres-secret
  namespace: autoservice
  labels:
    app.kubernetes.io/name: autoservice-postgres
    app.kubernetes.io/part-of: autoservice
type: Opaque
stringData:
  POSTGRES_DB: "autoservice"
  POSTGRES_USER: "postgres"
  POSTGRES_PASSWORD: "postgres"
