version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: autoservice-postgres
    restart: always

    environment:
      POSTGRES_DB: autoservice
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

    ports:
      - "5432:5432"

    volumes:
      - ./initdb.sql:/docker-entrypoint-initdb.d/01-init.sql
      - ./populate.sql:/docker-entrypoint-initdb.d/02-populate.sql

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

    networks:
      - autoservice-network

  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: autoservice-app
    restart: unless-stopped
    env_file:
      - ../local.variable.env
    ports:
      - "8088:8088"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/autoservice
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      APP_BASE_URL: http://localhost:8088
      MAIL_HOST: localhost
      MAIL_PORT: "1025"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - autoservice-network

volumes:
  postgres_data:

networks:
  autoservice-network:
    driver: bridge
