apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - 20-configmap-postgres.yaml
  - 21-initdb-postgres.yaml
  - 22-pvc-postgres.yaml
  - 23-deployment-postgres.yaml
  - 24-service-postgres.yaml
